experiment_dir: "/home/ji/experiments/halfcheetah"
verbose: tqdm
amp: true
device: cuda
tensorboard: true

train_config:
  dataset: halfcheetah
  dataset_root_path: /tmp/data
  epochs: 1
  # train
  max_episodes: 200
  val_episodes: 10
  train_iter: 10
  batch_size: 64
  # optimizer
  optimizer_config:
    name: adam
    arguments:
      lr: 2e-4
      betas: [0.5, 0.999]

model_config:
  name: spd
  buffer_size: 1000
  replay_size: 64
  teacher_smooth_factor: 1.0
  teacher_std: 1e-4
  # spd hparams
  recent_replay_ratio: 0.5
  sup_decay: 0.001
  threshold: 6.17103
  direction_threshold: 0.3
  sample_surprise_count: 42

search_space:
  train_config.env_seed:
    categorical_values: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ]
total_trials: 10
concurrent_trials: 10
search_algo: random
optim_metrics:
  val_reward: max
ignore_invalid_params: False
gpu_mb_per_experiment: 1000
cpus_per_experiment: 0.01
