experiment_dir: "/home/ji/experiments/tune_walker_spd"
verbose: silent
amp: true
device: cuda
tensorboard: true

train_config:
  dataset: walker
  dataset_root_path: /tmp/data
  epochs: 1
  # train
  max_episodes: 100
  val_episodes: 20
  train_iter: 3
  batch_size: 64
  # optimizer
  optimizer_config:
    name: adam
    arguments:
      lr: 1e-4
      betas: [0.5, 0.999]

model_config:
  name: spd
  buffer_size: 200
  replay_size: 64
  teacher_smooth_factor: 1.0
  teacher_std: 1e-4
  # spd hparams
  recent_replay_ratio: 0.40566
  sup_decay: 0.965039
  threshold: 9.73488
  direction_threshold: 0.264764

search_space:
  train_config.train_iter:
    value_range: [1, 5]
    value_type: int
  model_config.replay_size:
    value_range: [16, 200]
    value_type: int
  model_config.recent_replay_ratio:
    value_range: [0, 1.0]
    value_type: float
  model_config.sup_decay:
    value_range: [0.5, 1.0]
    value_type: float
  model_config.threshold:
    value_range: [5, 50]
    value_type: float
  model_config.direction_threshold:
    value_range: [0, 1.0]
    value_type: float
total_trials: 100
concurrent_trials: 10
search_algo: tpe
optim_metrics:
  avg_val_reward: max
ignore_invalid_params: True
gpu_mb_per_experiment: 1000
cpus_per_experiment: 0.05
