experiment_dir: "/home/ji/experiments"
logger_configs:
  - name: tensorboard
train_config:
  dataset: walker
  dataset_root_path: /tmp/data
  epochs: 1
  # train
  max_episodes: 100
  val_episodes: 100
  train_iter: 3
  batch_size: 65
  device: cuda
  amp: true
  debug: false
  resume: false
  # optimizer
  optimizer_config:
    name: adam
    arguments:
      lr: 2e-4
      betas: [0.5, 0.999]
model_config:
  name: spd
  buffer_size: 1000
  replay_size: 64
  teacher_smooth_factor: 1.0
  teacher_std: 1e-4
  # spd hparams
  recent_replay_ratio: 0.40566
  sup_decay: 0.965039
  threshold: 9.73488
  direction_threshold: 0.264764

tune:
  # train_config.train_iter: [ 1, 5 ]
  model_config.replay_size: [ 16, 512 ]
  model_config.recent_replay_ratio: [ 0, 1.0 ]
  model_config.sup_decay: [ 0.5, 1.0 ]
  model_config.threshold: [ 5, 50 ]
  model_config.direction_threshold: [ 0, 1.0 ]
total_trials: 100
concurrent_trials: 10
experiment_type: tpe
optim_directions: [[val_reward, max]]
ignore_errored_trials: True
num_experiment_per_gpu: 5
