experiment_dir: "/home/ji/experiments"
model_dir: "/home/ji/experiments/walker_spd"
logger_configs:
  - name: tensorboard
train_config:
  dataset: walker
  dataset_root_path: /tmp/data
  epochs: 1
  # train
  max_episodes: 100
  val_episodes: 100
  train_iter: 1
  batch_size: 64
  device: cuda
  amp: true
  debug: false
  resume: false
  # optimizer
  optimizer_config:
    name: adam
    arguments:
      lr: 2e-4
#      betas: [0.9, 0.999]
model_config:
  name: spd
  buffer_size: 1000
  replay_size: 64
  teacher_smooth_factor: 1.0
  teacher_std: 1e-4
  # spd hparams
  recent_replay_ratio: 0.5
  sup_decay: 0.8
  threshold: 10.0

tune:
  train_config.env_seed: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ]
total_trials: 20
concurrent_trials: 20
experiment_type: random
optim_directions: [[val_reward, max]]
ignore_errored_trials: True
num_experiment_per_gpu: 10
