experiment_dir: "/tmp/experiments"
verbose: tqdm
amp: true
device: cuda:0
tensorboard: true

train_config:
  dataset: hopper
  dataset_root_path: /tmp/data
  epochs: 1
  # train
  max_episodes: 100
  val_episodes: 1
  train_iter: 1500
  batch_size: 64
  # optimizer
  optimizer_config:
    name: adam
    arguments:
      lr: 2e-4
#      betas: [0.9, 0.999]

model_config:
  name: pd
  buffer_size: 2000
  replay_size: 128
  teacher_smooth_factor: 1.0
  teacher_std: 1e-4
