experiment_dir: "/tmp/experiments"
model_dir: "/tmp/experiments/test_spd"
logger_configs:
  - name: tensorboard
train_config:
  dataset: walker
  dataset_root_path: /tmp/data
  epochs: 1
  # train
  max_episodes: 100
  val_episodes: 100
  train_iter: 4
  batch_size: 64
  device: cuda:1
  amp: true
  debug: true
  resume: false
  # optimizer
  optimizer_config:
    name: adam
    arguments:
      lr: 2e-4
#      betas: [0.9, 0.999]
model_config:
  name: spd
  buffer_size: 2000
  replay_size: 128
  teacher_smooth_factor: 1.0
  teacher_std: 1e-4
  # spd hparams
  recent_replay_ratio: 0.40566
  sup_decay: 0.965039
  threshold: 9.73488
  direction_threshold: 0.264764
