experiment_dir: "/tmp/experiments"
verbose: tqdm
amp: true
device: cuda:0
tensorboard: true

train_config:
  dataset: walker
  dataset_root_path: /tmp/data
  epochs: 1
  # train
  max_episodes: 100
  val_episodes: 10
  train_iter: 3
  batch_size: 64
  # optimizer
  optimizer_config:
    name: adam
    arguments:
      lr: 2e-4
      betas: [0.5, 0.999]

model_config:
  name: spd
  buffer_size: 1000
  replay_size: 380
  teacher_smooth_factor: 1.0
  teacher_std: 1e-4
  # spd hparams
  recent_replay_ratio: 0.568297
  sup_decay: 0.893494
  threshold: 6.78839
  direction_threshold: 0.353084
